import React, { useEffect, useState } from 'react';
import apiClient from '../../api/apiClient';

const GROUPS = [
  ['Orders',['orders.read','orders.create','orders.manage']],
  ['Prescriptions',['prescription.read','prescription.write','prescription.manage']],
  ['Inventory',['inventory.read','inventory.write','inventory.import']],
  ['Billing',['billing.read','billing.write']],
  ['Referrals',['referrals.read','referrals.manage']],
  ['Tenants',['tenants.read','tenants.manage']],
  ['Users',['users.read','users.manage']],
  ['Platform',['platform.read','platform.manage']]
];
const title = s => s.split('.').map(x => x.charAt(0).toUpperCase()+x.slice(1)).join(' ');

export default function PlatformAccessControl(){
 const [users,setUsers]=useState([]),[selected,setSelected]=useState(null),[search,setSearch]=useState('');
 const [grants,setGrants]=useState([]),[revokes,setRevokes]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);try{const r=await apiClient.get('/api/v1/profile/access/users',{params:{search}});setUsers(r.data?.data||[]);}catch(e){setMessage(e.message||'Unable to load platform users.');}finally{setLoading(false);}};
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t);},[search]);
 const select=u=>{setSelected(u);setGrants(u.accessGrants||[]);setRevokes(u.accessRevokes||[]);setMessage('');};
 const setAccess=(code,allow)=>{if(allow){setRevokes(x=>x.filter(v=>v!==code));setGrants(x=>x.includes(code)?x:[...x,code]);}else{setGrants(x=>x.filter(v=>v!==code));setRevokes(x=>x.includes(code)?x:[...x,code]);}};
 const save=async()=>{if(!selected||saving)return;setSaving(true);try{const r=await apiClient.patch('/api/v1/profile/access/users/'+encodeURIComponent(selected.id),{grants,revokes});const u=r.data?.data||{};setSelected(x=>({...x,...u}));setUsers(xs=>xs.map(x=>x.id===selected.id?{...x,...u}:x));setMessage('Security assignment saved. Access changes apply on the next authenticated token refresh.');}catch(e){setMessage(e.message||'Could not save security assignment.');}finally{setSaving(false);}};
 return <section className="rounded-3xl border border-slate-200 bg-white shadow-sm overflow-hidden">
  <header className="bg-slate-950 text-white p-5 sm:p-6"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-300">Security Center</p><h2 className="text-xl sm:text-2xl font-black">Platform Access Control</h2><p className="mt-1 text-xs text-slate-300">Super Admin only. Assign or revoke access for pharmacy/platform users. Customer accounts are excluded.</p></div><span className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-[10px] font-black text-emerald-300">🔐 SUPER ADMIN</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, role or user ID…" className="mt-4 w-full rounded-xl px-3 py-2.5 text-xs text-slate-900 outline-none focus:ring-2 focus:ring-indigo-400"/></header>
  <div className="grid lg:grid-cols-[300px_1fr] min-h-[440px]">
   <aside className="border-b lg:border-b-0 lg:border-r border-slate-200 bg-slate-50 p-3"><div className="px-2 py-2 text-[10px] font-black uppercase tracking-wider text-slate-400">{loading?'Loading…':users.length+' platform users'}</div><div className="space-y-1.5 max-h-[560px] overflow-auto">{users.map(u=><button key={u.id} onClick={()=>select(u)} className={'w-full text-left rounded-xl p-3 border transition '+(selected?.id===u.id?'bg-indigo-50 border-indigo-200':'bg-white border-transparent hover:border-slate-200')}><div className="flex items-center gap-2"><span className="w-8 h-8 rounded-lg bg-indigo-100 text-indigo-700 flex items-center justify-center font-black text-xs">{(u.name||u.email||'?').charAt(0).toUpperCase()}</span><span className="min-w-0"><span className="block text-xs font-black text-slate-800 truncate">{u.name||'Unnamed user'}</span><span className="block text-[10px] text-slate-500 truncate">{u.email}</span></span></div><div className="mt-2 flex gap-1.5"><span className="text-[9px] font-black uppercase rounded-full bg-slate-100 text-slate-600 px-2 py-1">{u.role}</span>{u.tenantId&&<span className="text-[9px] rounded-full bg-blue-50 text-blue-700 px-2 py-1">Tenant</span>}</div></button>)}</div></aside>
   <main className="p-4 sm:p-6">{!selected?<div className="min-h-[360px] flex items-center justify-center text-center"><div><div className="text-4xl mb-3">🛡️</div><h3 className="font-black text-slate-900">Select a platform user</h3><p className="text-xs text-slate-500 mt-1">Review effective access before making a security assignment.</p></div></div>:<div className="space-y-5">
    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 border-b border-slate-100 pb-4"><div><h3 className="font-black text-slate-900">{selected.name||'Unnamed user'}</h3><p className="text-xs text-slate-500">{selected.email}</p><div className="flex gap-2 mt-2"><span className="text-[10px] font-black uppercase bg-indigo-50 text-indigo-700 rounded-full px-2 py-1">{selected.role}</span><span className="text-[10px] font-mono text-slate-400">ID: {selected.id}</span></div></div>{selected.effectiveSuperAdmin?<span className="text-[10px] font-black text-emerald-700 bg-emerald-50 rounded-full px-3 py-1.5">FULL ACCESS • LOCKED</span>:<button onClick={save} disabled={saving} className="rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-black px-4 py-2.5 disabled:opacity-50">{saving?'Saving…':'Save Security Assignment'}</button>}</div>
    {selected.effectiveSuperAdmin?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-900"><b>Complete platform access enabled.</b><p className="mt-1">Super Admin is never restricted by user-level grants or revokes.</p></div>:<div className="space-y-3">{GROUPS.map(g=><div key={g[0]} className="rounded-2xl border border-slate-200 p-3"><h4 className="text-xs font-black text-slate-800">{g[0]}</h4><p className="text-[10px] text-slate-400 mb-2">Role baseline + explicit user override</p><div className="grid sm:grid-cols-2 gap-2">{g[1].map(code=>{const revoked=revokes.includes(code),granted=grants.includes(code)||selected.permissions?.includes(code),roleGranted=selected.rolePermissions?.includes(code);return <div key={code} className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 px-3 py-2"><span className="text-[10px] font-bold text-slate-700">{title(code)}{!revoked&&roleGranted&&!grants.includes(code)?<span className="ml-1 text-[8px] text-blue-600">ROLE</span>:null}</span><div className="flex gap-1"><button onClick={()=>setAccess(code,true)} className={'text-[9px] font-black px-2 py-1 rounded-lg '+(!revoked&&granted?'bg-emerald-100 text-emerald-700':(!revoked&&roleGranted?'bg-blue-100 text-blue-700':'bg-white text-slate-400 border border-slate-200'))}>Allow</button><button onClick={()=>setAccess(code,false)} className={'text-[9px] font-black px-2 py-1 rounded-lg '+(revoked?'bg-rose-100 text-rose-700':'bg-white text-slate-400 border border-slate-200')}>Revoke</button></div></div>})}</div></div>)}</div>}
    {message&&<div className="rounded-xl bg-slate-50 border border-slate-200 px-3 py-2 text-xs text-slate-600">{message}</div>}
   </div>}</main>
  </div>
 </section>;
}